// import type { Metadata } from "next";
// import "./globals.css";
// import { dir } from 'i18next'
// import { languages } from '../i18n/settings'

// export async function generateStaticParams() {
//   return languages.map((lng) => ({ lng }))
// }


// const languages = ['en', 'de']

// export default function RootLayout({
//   children,
//   params: {
//     lng
//   }
// }) {
//   return (
//     <html lang={lng} dir={dir(lng)}>
//       <head />
//       <body>
//         {children}
//       </body>
//     </html>
//   )
// }


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import type { Metadata, LayoutProps } from "next";
import "./globals.css";
import { dir } from 'i18next'
import { languages } from '../i18n/settings'

// Generate static params for each language
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

// Define the type for the params object
type Params = {
  lng: string;
};

// Define the RootLayout component with correct types
const RootLayout = async ({
  children,
  params,
}: LayoutProps<Params>) => {
  const { lng } = params;
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;

// Define the metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
