import type { Metadata } from "next";
import "./globals.css";
import { dir } from 'i18next'
import { languages } from '../i18n/settings'

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}


const languages = ['en', 'de']

export default function RootLayout({
  children,
  params: {
    lng
  }
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body>
        {children}
      </body>
    </html>
  )
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


